name: Build and Test

on:
  push:
    branches:
      - dev
      - feat/*
      - test/*
      - fix/*
      - bugfix/*
      - hotfix/*
      - chore/*
      - refactor/*
      #- docs/*
      - ci/*
      - build/*
      - perf/*

  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
